language:
- node_js
node_js:
- '0.11'
before_install:
- sudo pip install awscli
- npm install -g grunt-cli bower
- npm install
install:
- bower install
- cd test && bower install && cd ../
script:
- grunt test
